#!/bin/bash

# List all files (including hidden ones) in the current directory in long format
ls -la

# List all files (including hidden ones) in the parent directory in long format
ls -la ..

# List all files (including hidden ones) in the /boot directory in long format
ls -la /boot
